backend:
  name: git-gateway
  branch: main
media_folder: "/public/uploads"
public_folder: "/uploads"
collections:
  - name: "fixed_pages"
    label: "Fixed Pages"
    editor:
      preview: false
    create: false
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/pages/index.md"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner image", name: "banner_image", widget: "image"}
          - {label: "Banner heading", name: "banner_heading", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
      - name: "about"
        label: "About"
        file: "src/pages/about.md"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Left banner image", name: "left_banner_image", widget: "image"}
          - {label: "Right banner image", name: "right_banner_image", widget: "image"}
          - {label: "Banner heading", name: "banner_heading", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}